description: stack para a criação de projetos de automação com cypress
name: qa-cypress-stack
display-name: qa-cypress-stack
picture: "cypress.jpg"
category: Frontend
compatibility: 
  - Javascript
technologies: 
  - Cypress
about: docs/about.md
use-cases:
  - title: Usando templates
    content: docs/use-case.md
    stackfile: stackfiles/default.yaml